# Generated by Django 6.0 on 2026-03-02 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='website',
        ),
    ]
