# Generated by Django 6.0 on 2026-01-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firm',
        ),
    ]
