# Generated by Django 6.0 on 2026-03-02 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_employer_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 8 digits', regex='^\\d{8}$')]),
        ),
    ]
