# Generated by Django 6.0 on 2026-04-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_job_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobslot",
            name="field_of_study",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="jobslot",
            name="intake",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
