# Generated by Django 6.0 on 2026-04-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_jobslot_field_of_study_jobslot_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='placement_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
