# Generated by Django 6.0 on 2026-04-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
